### ISSUE TITLE
Running Chat sample from remote server - socket cannot connect

### ISSUE THREAD

**Issue by acylum** [jxcore/jxm#15]
I'm trying to run the chat example on a remote server, but the websocket is not connecting - 

WebSocket connection to 'ws://0.0.0.0:8000/chat/jx?c=702a126251axT0@1112126' failed: Connection closed before receiving a handshake response

How do I change the ws address to my remote url?

**Comment by ktrzeciaknubisa** [comment]
Closing this because of no further activity.
