### ISSUE TITLE
Client side unsubscribe lead to an "Uncaught Reference Error: jx_obj is not defined"

### ISSUE THREAD

**Issue by KSchreyer** [jxcore/jxm#19]
Hi,
I'm running into an uncaught reference error while trying to unsubscribe from a channel. I can successfully join the channel, send a message to the channel and also call a server side method, which sends a message back to the channel. But when I'm trying to unsubscribe from the channel, I get the following error:

Uncaught ReferenceError: jx_obj is not defined in line 170 of jx?ms=connect

I'm running version 0.3.6 of jxm on node 0.10.33.

Kai

**Comment by ktrzeciaknubisa** [comment]
Thank you! Fixed now. Please try again and let us know!

**Comment by KSchreyer** [comment]
Now it works. Will you create a new version, to which we can update to from npm?

**Comment by obastemur** [comment]
updated on npm too
