### ISSUE TITLE
Howto disable WebSocket-Support in JXM?

### ISSUE THREAD

**Issue by KSchreyer** [jxcore/jxm#21]
After I moved our new JXM based messaging backend to our test server, I got the following error in the clients browser console (IP-Address was removed by myself):
`WebSocket connection to 'wss://xxx.xxx.xx.xx/channels/jx?c=699aNaNaxT0@1113650' failed: WebSocket opening handshake was canceled`

The cause is our Apache Webserver 2.2 in front of our system and the missing `mod_proxy_wstunnel` module, which  is only available for Apache 2.4. So in the long run we will update our system, but in the meanwhile I want my colleges to test the current implementation.

So I searched for a configuration option for the connection mechanisms. What I found was `jxcore.SocketDisabled = false;` in `backend/jx_browser_client.txt`. After I set it to `true`, the error disappears, but unfortunately neither the `jxcore.OnSubscription` nor the provided `callback` function got invoked in the clients browser after this change. :(

When I set `jxcore.SocketDisabled` back to `false`, everything works as expected.

Is there a way to disable the websocket functionality and fall back to long polling?

Thanks in advance for any help,
Kai

**Comment by ktrzeciaknubisa** [comment]
You are right, `jxcore.SocketDisabled = false;` in `backend/jx_browser_client.txt` should do the trick (I use that myself for testing), although much better would be config param for this, which we don't have yet :) 

However I never saw that any of the events are not called. Could you please double check and refresh the client after any code change on the server side (server restart)?

**Comment by KSchreyer** [comment]
I checked it again, on our testsystem and on my development machine. On my development machine I tested it also against IE8 in the default configuration (`jxcore.SocketDisabled = false;`). And it worked. And IE8 definitely does not support WebSockets. So the "normal" HTTP-Mode seems to work for me in the default configuration.

On the server side I see incoming requests as normal and no errors. When using node-debug I can see that the code parts, which are invoking the callback or the subscribeClient function, are getting executed. But on the client side, nothing happens. :(

I also checked in the browser development tools that the clients browser received the version where `jxcore.SocketDisabled` was set to `false`.

I'm using the latest version from npmjs.org (0.3.9).

Any further suggestions?

**Comment by KSchreyer** [comment]
One step further. It seems it only does not work in Chrome. In Firefox it works in HTTP-Mode.

My Chrome versions are `Version 43.0.2357.134 (64-bit)` on Linu and Mac OS X.

Can you please verify this on your side with jxm.io version 0.3.9?

**Comment by ktrzeciaknubisa** [comment]
Thank you for that info. I'll try to check it these days and let you know!

**Comment by KSchreyer** [comment]
`Safari Version 8.0.7 (10600.7.12)` and `Opera Version 30.0.1835.125` are showing the same behavior as Google Chrome.

IE11 works.

**Comment by ktrzeciaknubisa** [comment]
I've got some news: `jxcore.SocketDisabled = false;` seems to start working in Chrome and Safari once you enable `chunked = true` in *jx_node_settings.js*. I guess for that browser we'll just force `chunked` like it is for FireFox.

**Comment by KSchreyer** [comment]
Thanks for the news. I will check this when I'm back in office.

**Comment by KSchreyer** [comment]
After I switched `chunked` to `true`, I tested it successfully between the following browser:

Safari <--> Opera
Firefox <--> Chrome
Safari <--> Chrome

So, from my point of view, it works.

**Comment by ktrzeciaknubisa** [comment]
Thanks for an update. We'll also add the socket disabling option into node_settings soon, so the usage will be more straightforward.

**Comment by ktrzeciaknubisa** [comment]
The `socketDisabled` option is configurable now on master branch:

```js
server.setConfig("socketDisabled", true);
```
Regarding my previous suggestion as to change `chunked` option in `jx_node_settings.js` - in fact instead of this it is better and recommended to use the following:

```js
server.setConfig("chunked", true);
```
However it is not needed anymore. It may stay as `false` as well because it is forced now for some of the browsers. More on this in the docs: [chunked](http://jxcore.com/docs/jxcore-messaging.html#chunked).
