### ISSUE TITLE
redicilous

### ISSUE THREAD

**Issue by ZeevM3** [jxcore/jxm#22]
I have so many problems with jxm it's getting ridiculous...
Maybe you know why this one's happening:
If a mongodb db is empty, the program crashs.
No error msg, no logs, NOTHING.

I have plenty of code to handle this kind of scenarios, and also timer to check the db every once in a while.

Btw, like always, running the same code through node app.js works fine.

**Comment by ktrzeciaknubisa** [comment]
> I have so many problems with jxm it's getting ridiculous...

Do you really mean JXM or you meant JXcore? JXM has nothing to do with mongo, unless you employ both in your app.

Since we don't know what exactly you're doing and how the failing code looks like, we cannot say much about your case. 

> No error msg, no logs, NOTHING.

Did you try to subscribe to `uncaughtException` ?
