### ISSUE TITLE
Cannot call sendCallBack multiple times for the same client

### ISSUE THREAD

**Issue by BrunoRB** [jxcore/jxm#23]
I have a custom method at my server, something like:
```
var clientNames = {};
server.addJSMethod("logged", function (env, physicalId) {
      clientNames[physicalId] = env;
```

Inside this method I need to send some data to the calling client, but this data Needs to be sent in different calls, pseudo:

```
var params = {
	method: 'callback1',
	data: {}
};
server.sendCallBack(env, params);

params = {
	method: 'callback2',
	data: {}
};
server.sendCallBack(env, params);
```

The problem is that the client receives only the last sendCallBack call (the one with "method: 'callback2'"). So, this is expected? how can I send my data to this client without being tied to a single point?

**Comment by ktrzeciaknubisa** [comment]
Yes, `sendCallBack()` is designed to be called just once, as usually callbacks work. Your case would need something like `sendToClient()`, but we don't have it. What is left for you, is one of the following:

1. subscribe a client to a group and use `sendToGroup()`,
2. use `sendToAll()`, with params containing clientId value, and on client's side check: 
```js
    if (params.clientId === jxcore.GetClientId()) then do something
```

Both are just workarounds and are not perfect, I know :)

**Comment by BrunoRB** [comment]
I have been using both your suggestions as workarounds, they solve my problem but it seems to me that the ability to send data to a given client is a must for this kind of lib.

**Comment by ktrzeciaknubisa** [comment]
> but it seems to me that the ability to send data to a given client is a must for this kind of lib.

You may be right. But this is not so straightforward as one might think. The thing to be kept in mind is that clientId may change over time (reconnection/browser refresh etc.). 

If we would have `server.sendToClient()` it would probably use the internal clientId, but if the ID changes between the calls - some of them would not arrive. From that point of view the "group subscribing" approach that I proposed before is more reliable, as `sendToGroup()` operates on group names, which doesn't have to change (depending on implementation). If your solution would use a login system for users, then you would have some unique user name, and that may be used as a group name too.

I don't know how you implemented subscribing to groups, but if you made it from the client-side, you may also try from another end: server-side method [subscribeClient(env, groupName)](http://jxcore.com/docs/jxcore-messaging.html#subscribeclientenv-groupname) to see which you like more.
