### ISSUE TITLE
Errors in chrome-android

### ISSUE THREAD

**Issue by brunobg** [jxcore/jxm#24]
I get these errors in chrome-android:

POST http://192.168.1.100:2000/myapp/jx?co=1440544322111&io=1 404 (Not Found)
jxcore._Send	@	jx?ms=connect:1002
jxcore.Listen	@	jx?ms=connect:420
(anonymous function)	@	jx?ms=connect:537

The exact same page is fine in chrome-desktop. It's odd that it's trying to connect to port 2000 (where the http server is) instead of port 2666 (where jxm server is). 

`/myapp/jx/?ms=connect` is loaded correctly and has this: `window['jxcore'].ListenUrl='/myapp/jx';`

I'm also configuring this

```
server.setConfig("IPAddress", CONFS.server);
server.setConfig("httpServerPort", CONFS.jxmServerPort);
```

Any ideas why it's not working in android?

**Comment by ktrzeciaknubisa** [comment]
And which is the browser url, you're typing? Am I right, that your *index.html* is server by an http server 2000 and then it tries to call jxm on a 2666 port?

**Comment by brunobg** [comment]
Yes, the browser url is the index.html, served at 2000 (http://host:2000/index.html) and jxm at port 2666.

**Comment by ktrzeciaknubisa** [comment]
So I see from where the problem comes. I'll look into that.

BTW. any particular reason why to use two web servers? JXM alone is not enough for you?

**Comment by brunobg** [comment]
Thanks! The reason is that it's part of an application that uses the express framework. JXM alone has a simple webserver which is fine for many things, but we needed something more sophisticated.

**Comment by ktrzeciaknubisa** [comment]
JXM offers [setEngine()](http://jxcore.com/docs/jxcore-messaging.html#setengineapp) method. You can pass there an express instance and see how it works for you.

Or if you'll stay with two servers, you may use configuration option [clientExternal](http://jxcore.com/docs/jxcore-messaging.html#clientexternal). 

```js
server.setConfig("clientExternal", true);
server.start()
```

**Comment by brunobg** [comment]
Thank you! I had missed `clientExternal` from the docs, sorry, my mistake. I'll also check setEngine(). Things work now :)

**Comment by brunobg** [comment]
Reopening this, because even with clientExternal there are problems. Here's what happens:

1) First, I'm loading JXM with $.getScript(). This is because the server address is provided by the user. Also, I'm running it in Android.
2) The script is loaded. it calls jxcore.getScriptOrigin().
3) jxcore.getScriptOrigin() returns null. Why? document.getElementsByTagName("script"); returns as list of scripts that does not include the /app/jx script that was loaded with $.getScript()

My suggestion: make listenURL absolute.

**Comment by ktrzeciaknubisa** [comment]
Right. I guess we haven't tested JXM with jQuery. I'm not sure how soon we can pick this up. However you may try loading the script with something like below:

```js
var bdy = document.getElementsByTagName("body");
var _script = document.createElement("script"); 
_script.type = "text/javascript";
_script.src = params.url + "/jx?ms=connect";
bdy[0].appendChild(_script);
```

The `params.url` would be provided by your user.

**Comment by brunobg** [comment]
Yes, I'm using that as a workaround but it's difficult to know if the script was correctly loaded. _script.loaded() is called when it works, but not when it doesn't. 
The issue is not limited to jquery, but will happen if the script is evaluated dynamically instead of appended to the page.

**Comment by ktrzeciaknubisa** [comment]
If you would like to contribute and make things faster, you may propose some implementation and/or create a pull request. Then we'll take a look at it.

**Comment by brunobg** [comment]
Again, my suggestion is to make listenURL absolute.

**Comment by ktrzeciaknubisa** [comment]
If I remember correctly, the reason for current relative `listenURL` is that JXM is not returning to the client an IP/host used by the client to connect to JXM. 

Scenario: JXM runs on `http://0.0.0.0` and listens on all network interfaces, but client obviously uses one of them, e.g. `http://192.168.1.1`. From what I recall JXM misses fetching client's request IP in order to construct absolute url returned back to client, that's why it was easier to use relative one.

Now the client is trying to get JXM host by `jxcore.getScriptOrigin()`.

Yeap, this definitely needs some attention.

**Comment by brunobg** [comment]
You could fetch the HTTP request url when serving the .js file and use its domain/port.

**Comment by obastemur** [comment]
@brunobg is this still an issue?

**Comment by brunobg** [comment]
It is. The workaround works but it has that drawback I mentioned, and it still breaks loading with jquery.

**Comment by karaxuna** [comment]
See https://github.com/jxcore/jxm/pull/28
Does not depend on script src any more, so you can load with jQuery.

**Comment by ktrzeciaknubisa** [comment]
Hi @brunobg . @karaxuna made some updates. Can you please try your scenario with master branch and let us know? (the update is not on npm yet)

**Comment by ktrzeciaknubisa** [comment]
Closing this. Updates have been made and also jxm 0.4.0 have been published on npm repository.
