### ISSUE TITLE
How to retrieve Object Values from Callbacks in Java Client?

### ISSUE THREAD

**Issue by reever** [jxcore/jxm#29]
Hi, 

I am using NodeJS as Server side and Java Client as Client side and would like to sent a JSONObject from Server side nodeJS via Callback to JavaClient. I know that I have to use 
call function for that (as shown below) and retrieve my sent values through the Object arg. 
However, from this point on, I don't know how I get the values. The data is coming in checking logcat but I do not know how to retrieve the values out of the object arg. 

So my questions are:
When I sent my data from Server side, how do I retrieve my data through the object in the call function? When I check for the value I get something like this jxm.Client$JSON@49c155b, how do I cast this to something that I can use?

// Callbacks
final Callback callback = new Callback() {
    @Override
    public void call(Object arg, Integer err) throws Exception {
             System.out.println(arg.toString());
				});
};

Thanks in advance for your reply!
Benedict

**Comment by ktrzeciaknubisa** [comment]
Hi. Let's say, that your server sends this to client:

```js
    server.sendCallBack(env, { str_ : "ok", bool_ : true});
```

Then your Java client can receive it this way:

```java
Callback callback = new Callback() {
	@Override
	public void call(Object o, Integer err) throws Exception {
		if (err == 0) {
			Client.JSON obj = (JSON) o;
			System.out.println("str: " + obj.getValue("str_"));
			System.out.println("bool: " + obj.getValue("bool_"));
		}
	}
};
```

I'll make a note in documentation for this.

**Comment by reever** [comment]
This helps! Thanks for your quick reply!
