### ISSUE TITLE
How to send a message to a specific client?

### ISSUE THREAD

**Issue by reever** [jxcore/jxm#32]
How can I send a message in JXM from a Java Client to another Java Client with a specific userID in a channel instead of the whole group? I am referring to something similar to this (ex. from Socket.IO):
var socketid = users[userID];
io.sockets.socket(socketid).emit('for your eyes only');

Is it possible with JXM? 

Cheers

**Comment by obastemur** [comment]
@reever Why channel ? BTW, JXM bases on defining a server side method and calling it. Once the message or call on server you may deliver it to any client you want.

So define a method on the server that receives the client id and message and sends it back to that client. 

We might implement that internally though? If you think this approach works for the use case, you can also contribute this feature ?

**Comment by reever** [comment]
> Why channel?

Perhaps I am missing the point a bit, I understood that JXM, among many other benefits, allows me to have a messaging backend for a potential messaging client. That is my intention. However, the only option I can see that is implemented is to use the sentToGroup method. According to the docs this allows me to send a message to "all" clients that are subscribed to a certain "channel", however, I want to send messages directly from one Java Client to the other via their clientID.

> So define a method on the server that receives the client id and message and sends it back to that client. 

How do I define that method for a specific client if there is a sentToGroup method only. This method only allows me to send to clients that are inside a certain group or channel, according to the documentation, I cannot send to a specific client. I want to deliver to any client I want, as you said.
Please correct me if I am misunderstanding things here, really trying to wrap my head around these things.

> We might implement that internally though? If you think this approach works for the use case, you can also contribute this feature ?

If this is something that is not implemented yet, I am happy to contribute if you explain me where and how to start with this.

**Comment by ktrzeciaknubisa** [comment]
> How can I send a message in JXM from a Java Client to another Java Client with a specific userID in a channel instead of the whole group?

@reever Did you see the discussion https://github.com/jxcore/jxm/issues/23#issuecomment-130033628 ? Currently you cannot do it with JXM in as far as I know in a direct way and @obastemur probably meant something like proposal no 2. in the link above. 

If you feel like you can implement e.g. `SendToClient()` etc. you can fork the jxm repository, make the implementation and create a pull request.

Personally I think that currently registering each client to a separate group plus `sendToGroup()` is best.
