### ISSUE TITLE
JavaScript client send rate needs improvement?

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxm#33]
This applies just for client -> server direction.

I was rubbing my eyes and I couldn't believe, that JavaScript JXM client has a very low send rate: 1 message per 10 ms. This is due to `SendChecker()` being called by [setTimeout(..., 10)](https://github.com/jxcore/jxm/blob/master/backend/jx_browser_client.txt#L427).  `SendChecker()` sends only one message per call. I've tested it, I've seen it.

Do we want to improve that part?

**Comment by obastemur** [comment]
That's a feature rather than a limitation. If there are 100K messages during that 10ms, it will send 100K messages per 10ms..

**Comment by ktrzeciaknubisa** [comment]
Yeap, maybe you're right. Client shouldn't be able to send so much after all. I was just doing [memory leak](https://github.com/jxcore/jxm/issues/31) tests and so this came out to me.

```
Server received: 109 after 1442 ms
Server received: 192 after 2442 ms
Server received: 266 after 3440 ms
Server received: 347 after 4441 ms
Server received: 433 after 5441 ms
Server received: 507 after 6610 ms
```

507 messages from client to server during 6 secs should be sufficient for any client.
