### ISSUE TITLE
 jxm have background in CloudFlare?

### ISSUE THREAD

**Issue by matchsperlter** [jxcore/jxm#34]
Hello people support!
I am not fluent in english language. Your can answer questions like the title I wrote for determining jxm versatility, I very much hope the answer will be able to run offline in CloudFlare.

**Comment by ktrzeciaknubisa** [comment]
We never tried this. However you can try. In case of any problems, just let us know and we'll try to help.

**Comment by lrengunst** [comment]
I tried replacing each one process.env.OPENSHIFT_NODEJS_PORT
but the result is still like I'm wondering.
